# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup Android workload
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Keystore file
      run: |
        echo "${{ secrets.KEYSTORE }}" > keystore.base64.txt
        base64 -d keystore.base64.txt > "${{ secrets.KEYSTORE_NAME }}"
    - name: Publish
      run: dotnet build BikeRouteTracker/BikeRouteTracker.Android/BikeRouteTracker.Android.csproj -c Release -f net8.0-android /p:AndroidKeyStore=true /p:AndroidSigningKeyStore="${{ secrets.KEYSTORE_NAME }}" /p:AndroidSigningKeyAlias="${{ secrets.KEYSTORE_ALIAS }}" /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASS }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASS }}" --no-restore 
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
