# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Signing environment

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup Android workload
      run: dotnet workload restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup Keystore file
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYSTORE_NAME: ${{ secrets.KEYSTORE_NAME }}
      run: |
        echo "$KEYSTORE" > keystore.base64.txt
        base64 -d keystore.base64.txt > ${{ format("{0}/{1}", "/home/runner/work/BikeRouteTracker", "$KEYSTORE_NAME") }}
    - name: Publish
      env:
        KEYSTORE_NAME: ${{ secrets.KEYSTORE_NAME }}
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
      run: dotnet build BikeRouteTracker/BikeRouteTracker.Android/BikeRouteTracker.Android.csproj -c Release -f net8.0-android /p:AndroidPackageFormats=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=${{ format("{0}/{1}", "/home/runner/work/BikeRouteTracker", "$KEYSTORE_NAME") }} /p:AndroidSigningKeyAlias="$KEYSTORE_ALIAS" /p:AndroidSigningKeyPass="$KEYSTORE_PASS" /p:AndroidSigningStorePass="$KEYSTORE_PASS" --no-restore 
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
